version: '3'
volumes:
  pdn_upload_solicitudes:
services:
  solicitudes:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
      - 3200:3200
    volumes:
      - 'pdn_upload_solicitudes:/pdn_backend/solicitudes'
